services:
  loadtest:
    container_name: Tank
    image: yandex/yandex-tank
    volumes:
      - /home/vac/Desktop/pandora:/pandora
      - ./:/var/loadtest
      - /ssh-agent:/ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    network_mode: host